from PyQt5 import QtWidgets, QtCore, QtGui

class Ui_AWMWindow(object):
        
    def setupUi(self, AWMWindow):
        AWMWindow.setObjectName("AWMWindow")
        AWMWindow.resize(1025, 900)
        self.centralwidget = QtWidgets.QWidget(AWMWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.systemLabel = QtWidgets.QLabel(self.centralwidget)
        self.systemLabel.setGeometry(QtCore.QRect(800, 0, 180, 40))
        self.systemLabel.setObjectName("systemLabel")
        self.userWelcome = QtWidgets.QLineEdit(self.centralwidget)
        self.userWelcome.setEnabled(False)
        self.userWelcome.setGeometry(QtCore.QRect(0, 0, 280, 50))
        self.userWelcome.setObjectName("userWelcome")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(600, 60, 180, 50))
        self.updateButton.setObjectName("updateButton")
        self.boardButton = QtWidgets.QPushButton(self.centralwidget)
        self.boardButton.setGeometry(QtCore.QRect(800, 580, 200, 70))
        self.boardButton.setObjectName("boardButton")
        self.dataButton = QtWidgets.QPushButton(self.centralwidget)
        self.dataButton.setGeometry(QtCore.QRect(0, 345, 350, 60))
        self.dataButton.setObjectName("dataButton")
        self.dataLabel = QtWidgets.QLabel(self.centralwidget)
        self.dataLabel.setGeometry(QtCore.QRect(400, 300, 200, 40))
        self.dataLabel.setObjectName("dataLabel")
        self.dataText = QtWidgets.QTextEdit(self.centralwidget)
        self.dataText.setGeometry(QtCore.QRect(400, 345, 400, 60))
        self.dataText.setObjectName("dataName")
        self.gamemodes = QtWidgets.QComboBox(self.centralwidget)
        self.gamemodes.setGeometry(QtCore.QRect(600, 0, 180, 50))
        self.gamemodes.setObjectName("gamemodes")
        self.gamemodes.addItem("White-Box")
        self.gamemodes.addItem("Gray-Box")
        self.gamemodes.addItem("Black-Box")
        self.modelButton = QtWidgets.QPushButton(self.centralwidget)
        self.modelButton.setGeometry(QtCore.QRect(0, 220, 350, 60))
        self.modelButton.setObjectName("modelButton")
        self.modelLabel = QtWidgets.QLabel(self.centralwidget)
        self.modelLabel.setGeometry(QtCore.QRect(400, 180, 200, 40))
        self.modelLabel.setObjectName("modelName")
        self.modelText = QtWidgets.QTextEdit(self.centralwidget)
        self.modelText.setGeometry(QtCore.QRect(400, 220, 400, 60))
        self.modelText.setObjectName("modelName")
        self.modelALabel = QtWidgets.QLabel(self.centralwidget)
        self.modelALabel.setGeometry(QtCore.QRect(850, 180, 200, 40))
        self.modelALabel.setObjectName("Accuracy")
        self.modelTextA = QtWidgets.QTextEdit(self.centralwidget)
        self.modelTextA.setGeometry(QtCore.QRect(850, 220, 100, 60))
        self.modelTextA.setObjectName("modelAccuracy")
        self.signOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.signOutButton.setGeometry(QtCore.QRect(800, 500, 200, 70))
        self.signOutButton.setObjectName("signOutButton")
        AWMWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AWMWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 446, 22))
        self.menubar.setObjectName("menubar")
        AWMWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AWMWindow)
        self.statusbar.setObjectName("statusbar")
        AWMWindow.setStatusBar(self.statusbar)
        self.retranslateUi(AWMWindow)
        QtCore.QMetaObject.connectSlotsByName(AWMWindow)

    def retranslateUi(self, AWMWindow):
        _translate = QtCore.QCoreApplication.translate
        AWMWindow.setWindowTitle(_translate("AWMWindow", "Admin (White-Box Mode)"))
        self.updateButton.setText(_translate("AWMWindow", "Update"))
        self.systemLabel.setText(_translate("AWMWindow", "System Mode"))
        self.gamemodes.setItemText(0, _translate("AWMWindow", "White-Box"))
        self.gamemodes.setItemText(1, _translate("AWMWindow", "Gray-Box"))
        self.gamemodes.setItemText(2, _translate("AWMWindow", "Black-Box"))
        self.signOutButton.setText(_translate("AWMWindow", "Sign Out"))
        self.boardButton.setText(_translate("AWMWindow", "Leaderboard"))
        self.dataButton.setText(_translate("UWindow", "Submit Dataset"))
        self.dataLabel.setText(_translate("UWindow", "Dataset Name"))
        self.modelButton.setText(_translate("AWMWindow", "Submit a model"))
        self.modelLabel.setText(_translate("AWMWindow", "Model Name"))
        self.modelALabel.setText(_translate("AWMWindow", "Accuracy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AWMWindow = QtWidgets.QMainWindow()
    ui = Ui_AWMWindow()
    ui.setupUi(AWMWindow)
    AWMWindow.show()
    sys.exit(app.exec_())
