from PyQt5 import QtWidgets, QtCore, QtGui

class Ui_ABMWindow(object):

    def setupUi(self, ABMWindow):
        ABMWindow.setObjectName("ABMWindow")
        ABMWindow.resize(1025, 800)
        self.centralwidget = QtWidgets.QWidget(ABMWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userWelcome = QtWidgets.QLineEdit(self.centralwidget)
        self.userWelcome.setEnabled(False)
        self.userWelcome.setGeometry(QtCore.QRect(0, 0, 280, 50))
        self.userWelcome.setObjectName("userWelcome")
        self.systemLabel = QtWidgets.QLabel(self.centralwidget)
        self.systemLabel.setGeometry(QtCore.QRect(800, 0, 180, 40))
        self.systemLabel.setObjectName("systemLabel")
        self.dataButton = QtWidgets.QPushButton(self.centralwidget)
        self.dataButton.setGeometry(QtCore.QRect(0, 200, 350, 60))
        self.dataButton.setObjectName("dataButton")
        self.dataLabel = QtWidgets.QLabel(self.centralwidget)
        self.dataLabel.setGeometry(QtCore.QRect(400, 155, 200, 40))
        self.dataLabel.setObjectName("dataLabel")
        self.dataText = QtWidgets.QTextEdit(self.centralwidget)
        self.dataText.setGeometry(QtCore.QRect(400, 200, 400, 60))
        self.dataText.setObjectName("dataName")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(600, 60, 180, 50))
        self.updateButton.setObjectName("updateButton")
        self.gamemodes = QtWidgets.QComboBox(self.centralwidget)
        self.gamemodes.setGeometry(QtCore.QRect(600, 0, 180, 50))
        self.gamemodes.setObjectName("gamemodes")
        self.gamemodes.addItem("Black-Box")
        self.gamemodes.addItem("White-Box")
        self.gamemodes.addItem("Gray-Box")
        self.signOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.signOutButton.setGeometry(QtCore.QRect(800, 500, 200, 70))
        self.signOutButton.setObjectName("signOutButton")
        ABMWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ABMWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 446, 22))
        self.menubar.setObjectName("menubar")
        ABMWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ABMWindow)
        self.statusbar.setObjectName("statusbar")
        ABMWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ABMWindow)
        QtCore.QMetaObject.connectSlotsByName(ABMWindow)

    def retranslateUi(self, ABMWindow):
        _translate = QtCore.QCoreApplication.translate
        ABMWindow.setWindowTitle(_translate("ABMWindow", "Admin(Black-Box Mode)"))
        self.systemLabel.setText(_translate("ABMWindow", "System Mode"))
        self.updateButton.setText(_translate("ABMWindow", "Update"))
        self.signOutButton.setText(_translate("ABMWindow", "Sign Out"))
        self.dataButton.setText(_translate("UWindow", "Submit Dataset"))
        self.dataLabel.setText(_translate("UWindow", "Dataset Name"))
        self.gamemodes.setItemText(0, _translate("ABMWindow", "Black-Box"))
        self.gamemodes.setItemText(1, _translate("ABMWindow", "White-Box"))
        self.gamemodes.setItemText(2, _translate("ABMWindow", "Gray-Box"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ABMWindow = QtWidgets.QMainWindow()
    ui = Ui_ABMWindow()
    ui.setupUi(ABMWindow)
    ABMWindow.show()
    sys.exit(app.exec_())
