from PyQt5 import QtCore, QtGui, QtWidgets
import datasetDB as DDB

class Ui_AGMWindow(object):
        
    def setupUi(self, AGMWindow):
        AGMWindow.setObjectName("AGMWindow")
        AGMWindow.resize(1025, 900)
        self.centralwidget = QtWidgets.QWidget(AGMWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gamemodes = QtWidgets.QComboBox(self.centralwidget)
        self.gamemodes.setGeometry(QtCore.QRect(600, 0, 180, 50))
        self.gamemodes.setObjectName("gamemodes")
        self.gamemodes.addItem("Gray-Box")
        self.gamemodes.addItem("White-Box")
        self.gamemodes.addItem("Black-Box")
        self.systemLabel = QtWidgets.QLabel(self.centralwidget)
        self.systemLabel.setGeometry(QtCore.QRect(800, 0, 180, 40))
        self.systemLabel.setObjectName("systemLabel")
        self.userWelcome = QtWidgets.QLineEdit(self.centralwidget)
        self.userWelcome.setEnabled(False)
        self.userWelcome.setGeometry(QtCore.QRect(0, 0, 280, 50))
        self.userWelcome.setObjectName("userWelcome")
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        self.updateButton.setGeometry(QtCore.QRect(600, 60, 180, 50))
        self.updateButton.setObjectName("updateButton")
        self.dataButton = QtWidgets.QPushButton(self.centralwidget)
        self.dataButton.setGeometry(QtCore.QRect(0, 345, 350, 60))
        self.dataButton.setObjectName("dataButton")
        self.dataLabel = QtWidgets.QLabel(self.centralwidget)
        self.dataLabel.setGeometry(QtCore.QRect(400, 300, 200, 40))
        self.dataLabel.setObjectName("dataLabel")
        self.dataText = QtWidgets.QTextEdit(self.centralwidget)
        self.dataText.setGeometry(QtCore.QRect(400, 345, 400, 60))
        self.dataText.setObjectName("dataName")
        self.modelLabel = QtWidgets.QLabel(self.centralwidget)
        self.modelLabel.setGeometry(QtCore.QRect(400, 180, 200, 40))
        self.modelLabel.setObjectName("modelName")
        self.modelALabel = QtWidgets.QLabel(self.centralwidget)
        self.modelALabel.setGeometry(QtCore.QRect(850, 180, 200, 40))
        self.modelALabel.setObjectName("Accuracy")
        self.modelButton = QtWidgets.QPushButton(self.centralwidget)
        self.modelButton.setGeometry(QtCore.QRect(0, 220, 350, 60))
        self.modelButton.setObjectName("modelButton") 
        self.modelText = QtWidgets.QTextEdit(self.centralwidget)
        self.modelText.setGeometry(QtCore.QRect(400, 220, 400, 60))
        self.modelText.setObjectName("modelName")
        self.modelTextA = QtWidgets.QTextEdit(self.centralwidget)
        self.modelTextA.setGeometry(QtCore.QRect(850, 220, 100, 60))
        self.modelTextA.setObjectName("modelAccuracy")
        self.queryLabel = QtWidgets.QLabel(self.centralwidget)
        self.queryLabel.setGeometry(QtCore.QRect(0, 450, 100, 30))
        self.queryLabel.setObjectName("queryLabel")
        self.queryText = QtWidgets.QTextEdit(self.centralwidget)
        self.queryText.setGeometry(QtCore.QRect(0, 495, 200, 60))
        self.queryText.setObjectName("queryName")
        self.orLabel = QtWidgets.QLabel(self.centralwidget)
        self.orLabel.setGeometry(QtCore.QRect(230, 500, 40, 30))
        self.orLabel.setObjectName("orLabel")
        self.frequencyLabel = QtWidgets.QLabel(self.centralwidget)
        self.frequencyLabel.setGeometry(QtCore.QRect(300, 450, 150, 30))
        self.frequencyLabel.setObjectName("frequencyLabel")
        self.frequencyText = QtWidgets.QTextEdit(self.centralwidget)
        self.frequencyText.setGeometry(QtCore.QRect(300, 495, 200, 60))
        self.frequencyText.setObjectName("frequencyName")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(0, 600, 100, 30))
        self.outputLabel.setObjectName("outputLabel")
        self.outputText = QtWidgets.QTextEdit(self.centralwidget)
        self.outputText.setGeometry(QtCore.QRect(0, 645, 200, 60))
        self.outputText.setObjectName("outputName")
        self.or2Label = QtWidgets.QLabel(self.centralwidget)
        self.or2Label.setGeometry(QtCore.QRect(230, 650, 40, 30))
        self.or2Label.setObjectName("or2Label")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(300, 600, 200, 30))
        self.resultLabel.setObjectName("resultLabel")
        self.resultText = QtWidgets.QTextEdit(self.centralwidget)
        self.resultText.setGeometry(QtCore.QRect(300, 645, 200, 60))
        self.resultText.setObjectName("resultName")
        self.constraintsButton = QtWidgets.QPushButton(self.centralwidget)
        self.constraintsButton.setGeometry(QtCore.QRect(500, 570, 250, 60))
        self.constraintsButton.setObjectName("constraintsButton") 
        self.signOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.signOutButton.setGeometry(QtCore.QRect(800, 500, 200, 70))
        self.signOutButton.setObjectName("signOutButton")
        AGMWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AGMWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 446, 22))
        self.menubar.setObjectName("menubar")
        AGMWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AGMWindow)
        self.statusbar.setObjectName("statusbar")
        AGMWindow.setStatusBar(self.statusbar)
        self.retranslateUi(AGMWindow)
        QtCore.QMetaObject.connectSlotsByName(AGMWindow)

    def retranslateUi(self, AGMWindow):
        _translate = QtCore.QCoreApplication.translate
        AGMWindow.setWindowTitle(_translate("AGMWindow", "Admin (Gray-Box Mode)"))
        self.gamemodes.setItemText(0, _translate("AGMWindow", "Gray-Box"))
        self.gamemodes.setItemText(1, _translate("AGMWindow", "White-Box"))
        self.gamemodes.setItemText(2, _translate("AGMWindow", "Black-Box"))
        self.systemLabel.setText(_translate("AGMWindow", "System Mode"))
        self.updateButton.setText(_translate("AGMWindow", "Update"))
        self.signOutButton.setText(_translate("AGMWindow", "Sign Out"))
        self.dataButton.setText(_translate("AGMWindow", "Submit Dataset"))
        self.dataLabel.setText(_translate("AGMWindow", "Dataset Name"))
        self.frequencyLabel.setText(_translate("AGMWindow", "Frequency"))
        self.outputLabel.setText(_translate("AGMWindow", "Output"))
        self.resultLabel.setText(_translate("AGMWindow", "Result"))
        self.queryLabel.setText(_translate("AGMWindow", "Query"))
        self.orLabel.setText(_translate("AGMWindow", "OR"))
        self.or2Label.setText(_translate("AGMWindow", "OR"))
        self.constraintsButton.setText(_translate("AGMWindow", "Submit Constraints"))
        self.modelButton.setText(_translate("AGMWindow", "Submit a model"))
        self.modelLabel.setText(_translate("AGMWindow", "Model Name"))
        self.modelALabel.setText(_translate("AGMWindow", "Accuracy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AGMWindow = QtWidgets.QMainWindow()
    ui = Ui_AGMWindow()
    ui.setupUi(AGMWindow)
    AGMWindow.show()
    sys.exit(app.exec_())
