import datasetDB as DDB
from PyQt5 import QtWidgets, QtCore, QtGui


class Ui_UWMWindow(object):
    def loadDatasets(self):
        try:
            dataList = DDB.getDatasets()
            for x in dataList:
                self.datasetList.addItem(x[0])
        except Exception as e:
            print(e)

    def setupUi(self, UWMWindow):
        UWMWindow.setObjectName("UWMWindow")
        UWMWindow.resize(1000, 1200)
        self.centralwidget = QtWidgets.QWidget(UWMWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userWelcome = QtWidgets.QLineEdit(self.centralwidget)
        self.userWelcome.setEnabled(False)
        self.userWelcome.setGeometry(QtCore.QRect(0, 0, 400, 50))
        self.userWelcome.setObjectName("userWelcome")
        self.boardButton = QtWidgets.QPushButton(self.centralwidget)
        self.boardButton.setGeometry(QtCore.QRect(800, 70, 200, 70))
        self.boardButton.setObjectName("boardButton")
        self.signOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.signOutButton.setGeometry(QtCore.QRect(800, 0, 200, 60))
        self.signOutButton.setObjectName("signOutButton")
        self.fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileButton.setGeometry(QtCore.QRect(0, 100, 350, 60))
        self.fileButton.setObjectName("fileButton")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(400, 55, 200, 40))
        self.imageLabel.setObjectName("imageName")
        self.fileName = QtWidgets.QTextEdit(self.centralwidget)
        self.fileName.setGeometry(QtCore.QRect(400, 100, 395, 60))
        self.fileName.setObjectName("fileName")
        self.modelButton = QtWidgets.QPushButton(self.centralwidget)
        self.modelButton.setGeometry(QtCore.QRect(0, 220, 350, 60))
        self.modelButton.setObjectName("modelButton")
        self.modelLabel = QtWidgets.QLabel(self.centralwidget)
        self.modelLabel.setGeometry(QtCore.QRect(400, 180, 200, 40))
        self.modelLabel.setObjectName("modelName")
        self.modelText = QtWidgets.QTextEdit(self.centralwidget)
        self.modelText.setGeometry(QtCore.QRect(400, 220, 400, 60))
        self.modelText.setObjectName("modelName")
        self.modelALabel = QtWidgets.QLabel(self.centralwidget)
        self.modelALabel.setGeometry(QtCore.QRect(850, 180, 200, 40))
        self.modelALabel.setObjectName("Accuracy")
        self.modelTextA = QtWidgets.QTextEdit(self.centralwidget)
        self.modelTextA.setGeometry(QtCore.QRect(850, 220, 100, 60))
        self.modelTextA.setObjectName("modelAccuracy")
        self.datasetList = QtWidgets.QListWidget(self.centralwidget)
        self.datasetList.setGeometry(QtCore.QRect(20, 500, 300, 600))
        self.datasetList.setObjectName("datasetList")
        self.dataButton = QtWidgets.QPushButton(self.centralwidget)
        self.dataButton.setGeometry(QtCore.QRect(350, 550, 200, 60))
        self.dataButton.setObjectName("dataButton")
        self.imageList = QtWidgets.QListWidget(self.centralwidget)
        self.imageList.setGeometry(QtCore.QRect(20, 500, 300, 600))
        self.imageList.setObjectName("datasetList")
        self.imageButton = QtWidgets.QPushButton(self.centralwidget)
        self.imageButton.setGeometry(QtCore.QRect(350, 550, 200, 60))
        self.imageButton.setObjectName("imageButton")
        self.loadDatasets()
        UWMWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UWMWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 447, 22))
        self.menubar.setObjectName("menubar")
        UWMWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UWMWindow)
        self.statusbar.setObjectName("statusbar")
        UWMWindow.setStatusBar(self.statusbar)
        self.retranslateUi(UWMWindow)
        QtCore.QMetaObject.connectSlotsByName(UWMWindow)

    def retranslateUi(self, UWMWindow):
        _translate = QtCore.QCoreApplication.translate
        UWMWindow.setWindowTitle(_translate("UWMWindow", "User(White-Box Mode)"))
        self.imageLabel.setText(_translate("UWMWindow", "Image Name"))
        self.signOutButton.setText(_translate("UWMWindow", "Sign Out"))
        self.boardButton.setText(_translate("UWMWindow", "Leaderboard"))
        self.fileButton.setText(_translate("UWMWindow", "Submit an image"))
        self.modelButton.setText(_translate("UWMWindow", "Submit a model"))
        self.dataButton.setText(_translate("UWMWindow", "get Dataset"))
        self.modelLabel.setText(_translate("UWMWindow", "Model Name"))
        self.modelALabel.setText(_translate("UWMWindow", "Accuracy"))
